"""
Static lookup table mapping lowercase country names to ISO 3166-1 alpha-2 codes.

All countries present in seed_profiles.json are included, plus common
aliases and alternate spellings to improve NL query coverage.
"""

COUNTRY_MAP: dict[str, str] = {
    # Africa
    "algeria": "DZ",
    "angola": "AO",
    "benin": "BJ",
    "botswana": "BW",
    "burkina faso": "BF",
    "burundi": "BI",
    "cameroon": "CM",
    "cape verde": "CV",
    "cabo verde": "CV",
    "central african republic": "CF",
    "car": "CF",
    "chad": "TD",
    "comoros": "KM",
    "côte d'ivoire": "CI",
    "cote d'ivoire": "CI",
    "ivory coast": "CI",
    "djibouti": "DJ",
    "dr congo": "CD",
    "democratic republic of the congo": "CD",
    "drc": "CD",
    "congo dr": "CD",
    "egypt": "EG",
    "equatorial guinea": "GQ",
    "eritrea": "ER",
    "eswatini": "SZ",
    "swaziland": "SZ",
    "ethiopia": "ET",
    "gabon": "GA",
    "gambia": "GM",
    "the gambia": "GM",
    "ghana": "GH",
    "guinea": "GN",
    "guinea-bissau": "GW",
    "kenya": "KE",
    "lesotho": "LS",
    "liberia": "LR",
    "libya": "LY",
    "madagascar": "MG",
    "malawi": "MW",
    "mali": "ML",
    "mauritania": "MR",
    "mauritius": "MU",
    "morocco": "MA",
    "mozambique": "MZ",
    "namibia": "NA",
    "niger": "NE",
    "nigeria": "NG",
    "republic of the congo": "CG",
    "congo": "CG",
    "rwanda": "RW",
    "senegal": "SN",
    "seychelles": "SC",
    "sierra leone": "SL",
    "somalia": "SO",
    "south africa": "ZA",
    "south sudan": "SS",
    "sudan": "SD",
    "são tomé and príncipe": "ST",
    "sao tome and principe": "ST",
    "tanzania": "TZ",
    "togo": "TG",
    "tunisia": "TN",
    "uganda": "UG",
    "western sahara": "EH",
    "zambia": "ZM",
    "zimbabwe": "ZW",
    # Non-African countries present in seed data
    "australia": "AU",
    "brazil": "BR",
    "canada": "CA",
    "china": "CN",
    "france": "FR",
    "germany": "DE",
    "india": "IN",
    "japan": "JP",
    "united kingdom": "GB",
    "uk": "GB",
    "britain": "GB",
    "great britain": "GB",
    "united states": "US",
    "usa": "US",
    "us": "US",
    "america": "US",
}
